base:
  nacos-addr: http://139.159.133.183:8848
  test: hello test
server:
  port: 80
spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      server-addr:  ${base.nacos-addr} #huawei yun iaas
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: admin-service_router
          uri: lb://admin-service
          predicates:
            - Path=/admin/**
        - id: test
          uri: http://baidu.com/
          predicates:
            - Path=/test
    sentinel:
      transport:
        #dashboard: 139.159.133.183:8858
        dashboard: 127.0.0.1:8858
      datasource:
        ds1.nacos:
          serverAddr: ${base.nacos-addr}
          dataId: gw-flow
          ruleType: gw_flow
        ds2.nacos:
          serverAddr: ${base.nacos-addr}
          dataId: api-group
          ruleType: gw_api_group
