spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: admin-service_router
          uri: lb://admin-service
          predicates:
            - Path=/admin/**
        - id: test
          uri: http://baidu.com/
          predicates:
            - Path=/test
    sentinel:
      transport:
        #dashboard: 139.159.133.183:8858
        dashboard: 127.0.0.1:8080
      datasource:
        ds1.nacos:
          serverAddr: ${base.nacos-addr}
          dataId: gw-flow
          ruleType: gw_flow
        ds2.nacos:
          serverAddr: ${base.nacos-addr}
          dataId: api-group
          ruleType: gw_api_group
